### ISSUE TITLE
Multiple inputs

### ISSUE THREAD

**Issue by fortmarek** [SwiftDocOrg/github-wiki-publish-action#1]
Hi!

I was wondering if there is a way to define multiple directories as `inputs` parameter; unfortunately, it seems like Github actions do not support [arrays](https://github.community/t5/GitHub-Actions/Can-action-inputs-be-arrays/td-p/33776), I have tried [this](https://github.com/fortmarek/ACKategories/blob/7d1ec2c3ebcc871b3bcd87b1df3682b58b435ca1/.github/workflows/docs.yml) approach, but for obvious reasons that did not work either.

One workaround (as mentioned [here](https://github.community/t5/GitHub-Actions/Can-action-inputs-be-arrays/m-p/33800#M1644)) would be to parse `inputs` with space as a delimiter. If that seems like worth the effort, I can try to have a look.

**Comment by mattt** [comment]
Hi @fortmarek. Could you achieve the same effect by running the action twice with two different inputs? As far as I can tell, the work done here should keep intact existing files that aren't overwritten: 

https://github.com/SwiftDocOrg/github-wiki-publish-action/blob/a87db85ed06e4431be29cfdcb22b9653881305d0/entrypoint.sh#L53-L57

**Comment by fortmarek** [comment]
That, indeed, works, unfortunately, it is not a 100 % working solution since it overwrites `_Sidebar.md` (with list of types, etc.)

**Comment by mattt** [comment]
Wouldn't you have the same problem if it were possible to specify multiple inputs, though?

**Comment by fortmarek** [comment]
Running `swift-doc ACKategoriesCore ACKategories-iOS` works just fine, so I reckon if the action was rewritten to something like this:
```
runs:
  using: "docker"
  image: "Dockerfile"
  # parsed inputs
  args: ["${{ inputs.path.first }}", "${{ inputs.path.second }}"]
```
 it'd work just fine - as opposed to running what now boils down to `swift-doc ACKategoriesCore && swift-doc ACKategories-iOS`; or am I missing something?

Of course there is a question if you want to introduce such a workaround, but as a lot of Swift libraries do have multiple components, it might make sense to do so.

**Comment by mattt** [comment]
@fortmarek To clarify, this GitHub action only uploads contents to a project's GitHub wiki repository. Although `swift-doc` is the motivating use case, it can be used for any content.

**Comment by fortmarek** [comment]
Right, sorry, I got sidetracked a little bit, this is really more about [swift-doc](https://github.com/SwiftDocOrg/swift-doc/blob/master/action.yml) itself.
The solution would have to be a little different - taking inspiration from [here](https://github.com/softprops/action-gh-release#%EF%B8%8F-uploading-release-assets)

There would have to be an intermediate script that would be triggered from `action.yml` and in that script you'd have to parse the multi-line string and only then run `docker`.

Which is a little bit complicated, unfortunately.

**Comment by mattt** [comment]
@fortmarek Sorry, but I'm still not 100% clear about what problem you're facing. Would you mind taking a step back to explain what you're trying to accomplish?

**Comment by fortmarek** [comment]
Sure, sorry for making not myself clear. We have a library called `ACKategories` and for it we have two modules - `ACKategories-iOS` and `ACKategoriesCore`. Those translate to two directories.
Thus our project structure looks something like this:
```
-ACKategories
       -ACKategories-iOS
       -ACKategoriesCore
```

Locally, I can run `swiftdoc ACKategories-iOS ACKategoriesCore --output Documentation` to generate the valid documentation. That, unfortunately, does not seem to be possible using `swiftdoc`'s github action.

**Comment by mattt** [comment]
@fortmarek Thanks for clarifying. I just filed https://github.com/SwiftDocOrg/swift-doc/issues/19 to track the issue about array arguments.

Projects with multiple modules is absolutely something we want to support, but it may take some time to implement. In the meantime, though, you should be able to achieve what you're describing by running the swift-doc GitHub action twice with different input arguments?

**Comment by fortmarek** [comment]
Yes, we recognize it as a known limitation and went with the solution you suggested and it works fine for now 🙂 thanks for the help (and the patience 😄 ).

Closing as the new issue is a more appropriate place.
