### ISSUE TITLE
Doesn't support macos containers

### ISSUE THREAD

**Issue by dotdoom** [SwiftDocOrg/github-wiki-publish-action#12]
Looks like GitHub does not support dockerized actions in non-Linux containers. This action could be implemented as composite.

**Comment by mattt** [comment]
I believe that's correct. If you have a suggestion for how to improve this action, feel free to open a PR. Thanks!

**Comment by dotdoom** [comment]
Well that's one way to engage with community!
If you don't want to track deficiencies perhaps you'd consider adding it to documentation as WAI.
