### ISSUE TITLE
Ability to support images?

### ISSUE THREAD

**Issue by patrickklaeren** [SwiftDocOrg/github-wiki-publish-action#3]
Unless I'm doing something wrong, I cannot seem to be able to synchronise images, png, jpg or svg.

https://github.com/SwiftDocOrg/github-wiki-publish-action/blob/v1/entrypoint.sh#L53-L57

Seems to be filtering for only markdown files - which would be fine, but I would like to include images.

**Comment by mattt** [comment]
Your assessment is correct: currently, only files ending in `.md` are copied.

Taking another look at this, I think the current approach is needlessly limiting. I just opened a draft PR with #2 that replaces `find` / `cp` with `rsync`, which would copy over all files, including images. 

You can try this out for yourself by pointing to the `rsync` branch in your workflow file:

```yml
    - name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@rsync
```

Notably, this new version also deletes any files in the wiki that aren't present in the provided path. I'm thinking through the best way to configure this behavior, so if you have any ideas, I'd love to hear what you think.

**Comment by patrickklaeren** [comment]
@mattt Apologies for the delayed response - work has been hectic.

Thanks a lot, I will put this into testing and report back either way. Looks good though. I appreciate the fast response.
