### ISSUE TITLE
take headline as document name in sidebar

### ISSUE THREAD

**Issue by grindsa** [SwiftDocOrg/github-wiki-publish-action#5]
I am using the wiki-publish-action in my repo to keep the wiki updated. The update process as such works without issues however I noticed that the name of the markdown file will be used to name each page in the wiki side-bar. Is there any option to use the L1 headline (# foo) or a meta-tag from the document to enforce a certain page naming in the wiki side-bar?

Thank you for your help and have a nice day.

**Comment by mattt** [comment]
@grindsa Sorry, but I'm having trouble understanding your question. This action takes Markdown files and copies them verbatim to your project's wiki. It sounds like your issue is either the tool generating the content or how GitHub renders the wiki content.

**Comment by grindsa** [comment]
I did play with your code yesterday and the solution is much easier than I thought.  The title of a document in the wiki is based on the filename of the document. with ` ` replaced by `-`. So what I am looking for is an option to rename the document during copying and use either the headline or a meta-tag as filename. Let me create a PR for the meta-tag example.

**Comment by mattt** [comment]
@grindsa While I appreciate your willingness to share a PR that solves your problem, this functionality is out of scope for this particular tool. This action is for publishing what you have already, without making any changes. If you want to change what you have, that would be better-served by a separate step (e.g. running `sed` directly in your GitHub Actions workflow).
