### ISSUE TITLE
Workflow does not fail even if Wiki publish fails

### ISSUE THREAD

**Issue by brisberg** [SwiftDocOrg/github-wiki-publish-action#8]
If you attempt to run a workflow using this Action in a Github repo that fails, the workflow itself in the Actions tab succeeds. 

The cases I've found are is when the User has yet to initialize the Wiki (create first page)

I understand that in your README, you explicitly instruct people to create an initial Wiki page first. However, it isn't obvious to new people that without doing this, the Wiki repository doesn't actually exist.

The script always returns error code 0, so from the Github Actions menu the workflow appears to have succeeded. I had to inspect the workflow log to find the failed `git pull`.

It would be clearer if the workflow actually returned and error status in these cases.

----
Example logs of "successful" workflows:

```
-> Upload Documentation to Wiki1s

Run SwiftDocOrg/github-wiki-publish-action@v1
  with:
    path: wiki
  env:
    COMMIT_MESSAGE: Again
    GH_PERSONAL_ACCESS_TOKEN: ***
    WIKI_COMMIT_MESSAGE: Again
/usr/bin/docker run --name REDACTED --label REDACTED --workdir /github/workspace --rm -e COMMIT_MESSAGE -e GH_PERSONAL_ACCESS_TOKEN -e WIKI_COMMIT_MESSAGE -e INPUT_PATH -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/wip/wip":"/github/workspace" REDACTED:REDACTED  "wiki"
Initialized empty Git repository in /tmp/ci-XXXXIFcoKM/.git/
fatal: remote error: access denied or repository not exported: /1/nw/1a/fc/13/298559871/296491440.wiki.git
[master (root-commit) 7c3dc11] Again
 1 file changed, 2 insertions(+)
 create mode 100644 Page.md
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by mattt** [comment]
@brisberg You're totally right — the script should exit if `git pull` fails (or `git push`, for that matter). I've been bitten by this plenty myself, and would be very happy for this to be fixed, too.

I think #9 should resolve this. Could you please verify by rerunning with `SwiftDocOrg/github-wiki-publish-action@f00f10b`?

**Comment by brisberg** [comment]
Negative. The run still succeeded.

https://github.com/brisberg/wf-test/runs/1151412084

```
Run SwiftDocOrg/github-wiki-publish-action@f00f10b
  with:
    path: wiki
  env:
    COMMIT_MESSAGE: Added a wiki page
    GITHUB_PERSONAL_ACCESS_TOKEN: ***
    WIKI_COMMIT_MESSAGE: Added a wiki page
/usr/bin/docker run --name REDACTED --label 9e3346 --workdir /github/workspace --rm -e COMMIT_MESSAGE -e GITHUB_PERSONAL_ACCESS_TOKEN -e WIKI_COMMIT_MESSAGE -e INPUT_PATH -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/wf-test/wf-test":"/github/workspace" 9e3346:a7abf75623e847948411dd104f0757de  "wiki"
Initialized empty Git repository in /tmp/ci-XXXXDFPFic/.git/
fatal: remote error: access denied or repository not exported: /d/nw/d3/31/a8/299579656/297753069.wiki.git
[master (root-commit) 57c715a] Added a wiki page
 1 file changed, 1 insertion(+)
 create mode 100644 Page1.md
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

That repo has the workflow file I used. 
Note: That I had to use `GITHUB_PERSONAL_ACCESS_TOKEN` not `GH_PERSONAL_ACCESS_TOKEN` since I guess that dev branch is behind `v1`.

**Comment by mattt** [comment]
@brisberg Thanks for sharing your experience with this. Apologies for the late response.

I just rebased #9 against `v1` to use `GH_PERSONAL_ACCESS_TOKEN`. 4b9e9d10a762891799b6ae4095cc0905f108b121 should fix the subshell exit codes as per https://github.com/SwiftDocOrg/github-wiki-publish-action/pull/9#issuecomment-696952837. 

If you have a moment, it'd be great if you could retry again. (If not, no worries at all). I'll have a chance to test this out myself this week. I'm looking forward to resolving this issue soon.

**Comment by brisberg** [comment]
@mattt No problem at all :)

That change looks like it fixes the issue.

https://github.com/brisberg/wf-test/actions/runs/370843199

The action still correctly attempts to push to the repo, but the push fails (because I haven't initialized the Wiki) as expected.
That failure is correctly reported in the workflow action menu in the GitHub UI.

Thanks for the fix!

**Comment by mattt** [comment]
@brisberg Awesome. Thanks so much for verifying this fix — I really appreciate your help. Merging this in now.
